-- Insert 1
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Toyota',
    @modelo = 'Corolla',
    @anio = 2020,
    @placa = 'ABC123',
    @precioColones = 15000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 0,
    @transmision = 'Automática',
    @tipoVehiculo = 'Sedán',
    @puertas = 4,
    @largo = 4.62,
    @ancho = 1.77,
    @alto = 1.46,
    @materialAsientos = 'Cuero',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 0,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 0,
    @tableroMando = 'Digital',
    @tapizado = 'Cuero',
    @sistemaSonido = 'Premium',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/39/24/54/29392454_b1575e',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/39/24/54/29392454_18f46f';

-- Insert 2
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Toyota',
    @modelo = 'RAV4',
    @anio = 2019,
    @placa = 'DEF456',
    @precioColones = 20000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 1,
    @transmision = 'Automática',
    @tipoVehiculo = 'SUV',
    @puertas = 5,
    @largo = 4.60,
    @ancho = 1.85,
    @alto = 1.69,
    @materialAsientos = 'Tela',
    @tipoMotor = 'Híbrido',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 1,
    @camaraRetroceso = 1,
    @camara360 = 1,
    @sensoresLaterales = 1,
    @tableroMando = 'Digital',
    @tapizado = 'Tela',
    @sistemaSonido = 'Estándar',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/07/43/31/29074331_d26b05',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/07/43/31/29074331_6f7da8';

-- Insert 3
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Toyota',
    @modelo = 'Hilux',
    @anio = 2021,
    @placa = 'GHI789',
    @precioColones = 25000000.00,
    @esNegociable = 0,
    @recibeOtrosVehiculos = 1,
    @transmision = 'Manual',
    @tipoVehiculo = 'Pick-up',
    @puertas = 4,
    @largo = 5.30,
    @ancho = 1.85,
    @alto = 1.80,
    @materialAsientos = 'Cuero',
    @tipoMotor = 'Diesel',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 1,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 1,
    @tableroMando = 'Analógico',
    @tapizado = 'Cuero',
    @sistemaSonido = 'Estándar',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/44/84/89/29448489_573ec4',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/44/84/89/29448489_ab7a62';

EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Hyundai',
    @modelo = 'Tucson',
    @anio = 2022,
    @placa = 'JKL012',
    @precioColones = 18000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 0,
    @transmision = 'Automática',
    @tipoVehiculo = 'SUV',
    @puertas = 5,
    @largo = 4.50,
    @ancho = 1.85,
    @alto = 1.65,
    @materialAsientos = 'Tela',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 0,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 0,
    @tableroMando = 'Digital',
    @tapizado = 'Tela',
    @sistemaSonido = 'Premium',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/27/96/63/49/27966349_eecb8a',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/27/96/63/49/27966349_93ae30';

-- Insert 5
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Hyundai',
    @modelo = 'Elantra',
    @anio = 2020,
    @placa = 'MNO345',
    @precioColones = 12000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 1,
    @transmision = 'Automática',
    @tipoVehiculo = 'Sedán',
    @puertas = 4,
    @largo = 4.65,
    @ancho = 1.80,
    @alto = 1.45,
    @materialAsientos = 'Cuero',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 0,
    @sensoresDelanteros = 0,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 0,
    @tableroMando = 'Analógico',
    @tapizado = 'Cuero',
    @sistemaSonido = 'Estándar',
    @condicion = 2,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/42/92/85/29429285_efa69b',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/42/92/85/29429285_dff2f9';

-- Insert 6
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Mazda',
    @modelo = 'CX-5',
    @anio = 2021,
    @placa = 'PQR678',
    @precioColones = 22000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 1,
    @transmision = 'Automática',
    @tipoVehiculo = 'SUV',
    @puertas = 5,
    @largo = 4.55,
    @ancho = 1.85,
    @alto = 1.67,
    @materialAsientos = 'Cuero',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 1,
    @camaraRetroceso = 1,
    @camara360 = 1,
    @sensoresLaterales = 1,
    @tableroMando = 'Digital',
    @tapizado = 'Cuero',
    @sistemaSonido = 'Premium',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/28/92/38/29289238_5e066d',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/28/92/38/29289238_b351a8';

-- Insert 7
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Mazda',
    @modelo = '3',
    @anio = 2018,
    @placa = 'STU901',
    @precioColones = 10000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 0,
    @transmision = 'Manual',
    @tipoVehiculo = 'Sedán',
    @puertas = 4,
    @largo = 4.58,
    @ancho = 1.80,
    @alto = 1.45,
    @materialAsientos = 'Tela',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 0,
    @sensoresDelanteros = 0,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 0,
    @tableroMando = 'Analógico',
    @tapizado = 'Tela',
    @sistemaSonido = 'Estándar',
    @condicion = 3,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/51/25/39/29512539_3a5041',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_s/f_auto/v1/cr/29/52/34/97/29523497_bbae0e';

-- Insert 8
EXEC InsertarVehiculo
    @usuarioId = 1,
    @marca = 'Honda',
    @modelo = 'Civic',
    @anio = 2019,
    @placa = 'VWX234',
    @precioColones = 14000000.00,
    @esNegociable = 1,
    @recibeOtrosVehiculos = 1,
    @transmision = 'Automática',
    @tipoVehiculo = 'Sedán',
    @puertas = 4,
    @largo = 4.63,
    @ancho = 1.80,
    @alto = 1.42,
    @materialAsientos = 'Cuero',
    @tipoMotor = 'Gasolina',
    @vidriosElectricos = 1,
    @espejosElectricos = 1,
    @sensoresTraseros = 1,
    @sensoresDelanteros = 1,
    @camaraRetroceso = 1,
    @camara360 = 0,
    @sensoresLaterales = 1,
    @tableroMando = 'Digital',
    @tapizado = 'Cuero',
    @sistemaSonido = 'Premium',
    @condicion = 1,
    @estaEnLeasing = 0,
    @fotosInternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/52/65/24/29526524_b0601d',
    @fotosExternas = 'https://photos.encuentra24.com/t_or_fh_l/f_auto/v1/cr/29/53/54/95/29535495_d509bf';



-- Continúan los inserts 4 al 10 con otras marcas y configuraciones...
INSERT INTO Usuarios (
    tipoIdentificacion,
    numeroIdentificacion,
    nombre,
    apellido1,
    apellido2,
    nacionalidad,
    fechaNacimiento,
    correo,
    contrasena,
    telefono,
    provincia,
    canton,
    distrito,
    idiomaInterfaz,
    estaVerificado
)
VALUES (
    'cédula',                -- Tipo de identificación
    '123456789',             -- Número de identificación único
    'Juan',                  -- Nombre
    'Pérez',                 -- Primer apellido
    'Gómez',                 -- Segundo apellido
    'Costarricense',         -- Nacionalidad
    '1990-05-14',            -- Fecha de nacimiento
    'juan.perez@example.com',-- Correo electrónico único
    HASHBYTES('SHA2_256', 'contraseña123'), -- Contraseña (hashed para seguridad)
    '88881234',              -- Teléfono
    'San José',              -- Provincia
    'Central',               -- Cantón
    'Carmen',                -- Distrito
    'es-CR',                 -- Idioma de la interfaz
    1                        -- Verificación: el usuario está validado
);

select * from Vehiculos